version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Измените порт здесь
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web